server:
  port: 18080
spring:
  datasource:
    url: jdbc:mysql://lyh543.cn:3306/aurora?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver